### ISSUE TITLE
Title field not correctly recognized on pageload

### ISSUE THREAD

**Issue by alxy** [Yoast/YoastSEO.js#1117]
## What did you expect to happen?
The title field is not recognized as long as I do not focus the the field in the SnippetPreview's configuration area. I need to click into the Preview box, after then it updates. For other fields, like the Slug (URL path) the behavior works as expected.
After initialization I do call ``app.refresh();``.
https://www.dropbox.com/s/zf34mrtnn1lju2m/Screenshot%202017-03-06%2020.41.54.png?dl=0

If needed, I can provide my entire source code. However, as this is a third party integration, it might be a bit difficult to test. The initialization process looks as follows:
```
SEOAnalyzer.prototype.initSnippetPreview = function () {
        var that = this;
        return new SnippetPreview({
            targetElement: that.el,
            callbacks: {
                saveSnippetData: function (data) {
                    that.inputFields.urlPathField.val(data.urlPath);
                    that.inputFields.titleField.val(data.title);
                    that.inputFields.metaDescriptionField.val(data.metaDesc);

                }
            },
            baseURL: that.options['baseUrl'],
            data: {
                "urlPath": that.inputFields.urlPathField.val(),
                "title": that.inputFields.titleField.val(),
                "metaDesc": that.inputFields.metaDescriptionField.val()
            }
        });
    };

    SEOAnalyzer.prototype.initApp = function (snippetPreview) {
        var that = this;

        return new App({
            snippetPreview: snippetPreview,
            locale: this.options['locale'],
            translations: this.options['translations'],
            targets: {
                output: "output",
                contentOutput: "contentOutput"
            },
            callbacks: {
                getData: function () {
                    return {
                        keyword: that.inputFields.focusKeywordField.val(),
                        text: that.inputFields.contentField.froalaEditor('html.get'),
                        metaTitle: that.inputFields.titleField.val(), // Find out what this is good for
                        title: that.inputFields.titleField.val(),
                        excerpt: that.inputFields.excerptField.val()
                    };
                }
          }
                
    };
```
Called like this:
```
this.snippetPreview = this.initSnippetPreview();
        this.app = this.initApp(this.snippetPreview);

        this.setupListeners();

        this.app.refresh();
```

## Technical info

* Platform: Standalone
* Platform version: -
* Yoast SEO version: develop (latest)

**Comment by terw-dan** [comment]
Thanks for reporting this issue. 

In the getData callback you send the title to the snippetPreview. Can you check if that has any value at that moment? We fall back to a default is no title is given ( https://github.com/Yoast/YoastSEO.js/blob/develop/js/app.js#L40 ) it might be that that is overwritten by sending an empty string to it. 

Do you have a live version of this code? This might make it easier to see if the data is set where it should be.

**Comment by alxy** [comment]
Hi, thanks for your answer.
You can test the code [here](http://webdesign-guth.de/october/backend/rainlab/blog/posts/update/5) using demo / demo as login credentials.

For testing purpose, I inserted a static string in the ``getData()`` callback, but still the immediate prompt is "Please create a page title."

**Comment by terw-dan** [comment]
Thanks for the link. 
I had a quick look at it. The pagetitle is based on the width of the title (it used to be the number of characters, but that has changed to comply with the way google handles titles). 

It seems the title width isn't set, and this always returns 0. And with a width of 0 we always assume there is no title set. 
I'd suggest checking if the titleWidth is set in the paper ( https://github.com/Yoast/YoastSEO.js/blob/develop/js/values/Paper.js#L110 ), or if this defaults to 0. 

As far as I can see the title is set, because if I enter a keyword (that is not the first in the title), the assessment will show `The SEO title contains the focus keyword, but it does not appear at the beginning; try and move it to the beginning.`

**Comment by alxy** [comment]
You are right, it defaults to 0. Probably because the element is not beein properly rendered before it gets the focus: https://github.com/Yoast/YoastSEO.js/blob/develop/js/snippetPreview.js#L1201

How can I solve this problem in an elegant way? I can set some default value different from 0 to the ``titleWidth``, but that sounds kind of hackerish.

**Comment by terw-dan** [comment]
I think I figured out where this goes wrong in your case. 

The offsetWidth is only calculated when the element is rendered on the page. Since you have tabs for settings, it seems that the element offset is 0. 

If I put `document.getElementById( "snippet_title" ).offsetWidth`  in the javascript console on a tab where the title element isn't visible, the offsetWidth is 0. If I do the same with the tab active with the snippet preview, the offsetWidth will be something like 457, at least a value. 

In our example we don't have this problem, since all elements are rendered at the same time. 

Setting the default value to anything else then 0 wouldn't solve the issue, since the check is done and overwrites the default, thus setting it back to 0.  
The best way to solve this is to either make sure the element is rendered on the page at all times (even when it isn't visible), Or to make sure the offsetWidth is stored in a variable and use that for the title width assessment.

**Comment by alxy** [comment]
You appear to be right, however, I don't know what exactly I need to change in my current code to make it render appropriately (I think I would prefer the first method, saying the title should be rendered at all time).

I know this is not directly related to the YoastSEO.js project, but can you think of any nice way to accomplish this?

**Comment by terw-dan** [comment]
Hi @alxy 

Since this isn't directly related I cannot give you full support. But of course I can give some hints. 

What you could do is hide the snippet preview using `visibility:hidden` on the container and show and hide this. Because it is still rendered the offsetWidth should not be set to 0, but have an actual value.

**Comment by alxy** [comment]
Hi @terw-dan ,

thanks for your input and help. This does indeed work, however it required me to do a little change to the snippetPreview: Currently, there is no chance to modify the ``titleWidth`` once the preview is initialized (at this stage it is possible to pass an initial value via the ``data`` object). The only method, that has ability to update the value, is [measureTitle()](https://github.com/Yoast/YoastSEO.js/blob/develop/js/snippetPreview.js#L1201).
This is why I propose to add a setter to the Preview for the ``titleWidth``. That would allow for setups where the preview is not always rendered, e.g. in tabbed layouts.
My code proposal is as follows:

```
/**
 * Allows to manually set the title width.
 * This may be useful in setups where the title field will not always be rendered on the page.
 * 
 * @param {Number} titleWidth The width of the title in pixels.
 */
SnippetPreview.prototype.setTitleWidth = function(titleWidth) {
	this.data.titleWidth = titleWidth;
};
```

Is there any chance to get that merged if I prepare a PR?

**Comment by terw-dan** [comment]
Hi @alxy, 

thanks for your input. At Yoast we always value contributions. So feel free to create a PR for this. However I cannot promise we can integrate it at short notice. The SnippetPreview is integrated on quite a few platforms, so this has to be tested to make sure it still works everywhere. 
But if you create a PR we can take a look at it to see if we can integrate it in our plugin.

**Comment by alxy** [comment]
I have provided the corresponding PR and now I am requesting a status update on this one, as I did not get any feedback to the code provided. (Is it ok, are there obvious issues?) If needed, I can also write a spec for it, however Im unsure what exactly could be edge cases that need to be covered.
