### ISSUE TITLE
Implement dynamic imports for YoastSEO.js assessments that use large word lists

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#1463]
Currently all word lists are imported using `require` at the beginning of a researcher or helper file. E.g., from `/YoastSEO.js/src/stringProcessing/relevantWords.js`:

> let germanFunctionWords = require( "../researches/german/functionWords.js" );
> let englishFunctionWords = require( "../researches/english/functionWords.js" );
> let dutchFunctionWords = require( "../researches/dutch/functionWords.js" );
> let spanishFunctionWords = require( "../researches/spanish/functionWords.js" );
> let italianFunctionWords = require( "../researches/italian/functionWords.js" );
> let frenchFunctionWords = require( "../researches/french/functionWords.js" );
> let portugueseFunctionWords = require( "../researches/portuguese/functionWords.js" );

This is suboptimal, because word lists for all languages are imported regardless of the actual language that is analysed.

We need to implement dynamic imports that will work for webpack.

Fallback option: try/catch around require. See an example [here](https://github.com/Yoast/YoastSEO.js/blob/develop/examples/webpack/src/utils/getMorphologyData.js#L9).

**Comment by igorschoester** [comment]
The issue scope was to try out webpack dynamic imports, I did not succeed with this due to:
- Webpack chunk names / chunks not being found.
- Which babel plugin should we use? import does not use chunknames while using the <7 currently in wordpress-seo. Falling back on `require.ensure` works.
- Async / sync difference - did not get there yet.

A new solution would be to not use webpack to chunk this. But just read them from the files directly (via the plugin).
This could work for the AnalysisWebWorker similar to how the morphology files are being loaded. Through `worker.initialize( { functionWords } )` or something along those lines.
The downside is that this would not be backwards compatible with the current implementation.

Therefore, the first goal is: _What would be the backwards compatible version?_


## Backwards compatible version
Trying to find a solution for a dynamic import in YoastSEO.js itself. The chunks do seem to be the best solution for this since webpack itself takes on the task of the web requests. With a normal require the file has to be in the bundle to work and that is not what we want. When excluding the file from the bundle there would need to be an external source to serve the files. That makes it no longer a backwards compatible way.
The dynamic import (`require.ensure` version) loading inside of a webworker seems to depend on the window object. With a `output.globalObject: "this"` I get beyond the `jsonpFunction` not being found, but then it is failing at `requireEnsure`. I found this issue about this: https://github.com/webpack/webpack/issues/6472 Which could offer a solution with importScripts, but I stopped there as this would take a lot more time. 
A different loader, but this is a starting project of one person it seems: https://github.com/whitecolor/lp-loader


## Resources found
- Webpack dynamic import https://webpack.js.org/api/module-methods/#import
- Medium article https://medium.com/front-end-hacking/webpack-and-dynamic-imports-doing-it-right-72549ff49234
- Babel plugin 7.1.0 https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import
- Babel plugin < 7 (currently in wordpress-seo) https://github.com/airbnb/babel-plugin-dynamic-import-webpack

**Comment by igorschoester** [comment]
## Steps of the backwards incompatible version

1. Implementation in the worker.
This can be done via `worker.initialize( { localizations } )`. Where the localizations is an object that can hold multiple locales `en: {}, nl: {},`. When called it will just get merged to the current localizations in the worker.
1. Migration path and a **guide**.
This could be `localizations = require( "yoastseo/localizations" )` for all the languages. Then `require( "yoastseo/localizations/en" )` for only English.
1. Yoast SEO using the partial method and a **guide**.
This should be the above in `wordpress-seo` but then the user langauge should be loaded. Maybe in PHP so that we don't get the async problem.
1. Console warning when calling analyze when the localization data has not been set yet.
1. Breaking change: Remove bundling in the worker.

Props to @atimmer
