### ISSUE TITLE
AnalysisWebWorker error with dev-server and Firefox

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1728]
When building the plugin with the dev-server and opening a post or taxonomy page in Firefox, a AnalysisWebWorker error occurs. This error doesn't occur in Chrome. It also doesn't occur in Firefox when using grunt to build. We should investigate what causes this error.

<img width="499" alt="screen shot 2018-08-23 at 13 27 45" src="https://user-images.githubusercontent.com/27805437/44523009-b08d5800-a6d8-11e8-8d32-c1386d099755.png">

**Comment by igorschoester** [comment]
`webpack-dev-server` and Firefox's Worker API do not get along for some reason.

What I saw is that in Firefox the worker is not being fetched, therefore there is no actual worker. This is my best guess to where the error comes from. As even removing all the code of the worker will still trigger the error. There is nothing to debug because it will not get called.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 419873 when this conversation has been closed.

**Comment by rmarcano** [comment]
Related https://github.com/Yoast/wordpress-seo/issues/10875

**Comment by atimmer** [comment]
There is a chance this is solved by adding the following header: `Content-Security-Policy: worker-src * 'unsafe-inline' 'unsafe-eval' data: blob:;`

**Comment by atimmer** [comment]
I believe this issue is fixed by https://github.com/Yoast/javascript/pull/391.

@manuelaugustin if/when you have the time can you verify?

**Comment by igorschoester** [comment]
That seems to have solved it 😄
