### ISSUE TITLE
Keyword distribution highlight should be inversed

### ISSUE THREAD

**Issue by jdevalk** [Yoast/YoastSEO.js#1863]
Basically it should highlight exactly the same as the keyphrase density highlight.

**Comment by manuelaugustin** [comment]
I'll revert the marking functionality to highlighting keyphrases.

Just to be clear, however, it won't be exactly the same as the markings for keyword density. For keyword density, we only count the full keyphrase within a sentence as a match. So if your keyphrase is `social media strategy`, `social`, `media` and `strategy` need to appear somewhere in the sentence to count as a match and these words get marked.

In keyword distribution, finding matches works a bit differently. For example, you also get some 'points' for partial matches. So just having `social` and `media` in the sentence (even if `strategy` is absent) will give you some partial points. I think it makes sense to mark the words for which you actually get points. This means you'd also get markings on words in cases where you won't get them in keyword density.

So overall the markings would be very similar as in keyword density (because we mark matches of the keyphrase) but thet won't be exactly the same, because we define 'match' differently in the two assessments.

Please let me know if that's okay @jdevalk

**Comment by jdevalk** [comment]
Sounds good!!
