### ISSUE TITLE
Check the export of subheadingsKeywordAssessment

### ISSUE THREAD

**Issue by afercia** [Yoast/YoastSEO.js#1937]
Not sure this export is correct:

https://github.com/Yoast/YoastSEO.js/blob/7773587cb3ac1474f995a8fa3232f70f8807654b/src/assessments/seo/subheadingsKeywordAssessment.js#L145

I'm getting various warnings:
```
[1] WARNING in ./node_modules/yoastseo/src/seoAssessor.js
[1] 40:6-24 "export 'default' (imported as 'SubheadingsKeyword') was not found in './assessments/seo/subheadingsKeywordAssessment'
```

when testing the yoast-component standalone, branch `release-yoast-seo/9.1`.

To my knowledge, it should be `export default SubHeadingsKeywordAssessment;`

**Comment by igorschoester** [comment]
https://github.com/Yoast/YoastSEO.js/blob/7773587cb3ac1474f995a8fa3232f70f8807654b/src/assessments/seo/subheadingsKeywordAssessment.js#L145

The above is fixed on `develop` with https://github.com/Yoast/YoastSEO.js/pull/1919
Not sure if it is worth fixing for `9.1`. Does this impact more than the stand-alone?

**Comment by manuelaugustin** [comment]
As far as we can see this only impacts the stand-alone on the release branch. The plugin build worked without any errors on the release branch. Also, the error doesn't occur when building the stand-alone on develop.

Since the impact of this issue seems to be so limited, we've concluded that we're not going to implement the fix on the release branch.
