### ISSUE TITLE
add 'clearly' to the english transition words

### ISSUE THREAD

**Issue by SergeantRaccoon** [Yoast/YoastSEO.js#1980]
## What did you expect to happen?
I expected our analysis to recognize the word `clearly` as a transition word when it is used as such.

## What happened instead?
Our analysis did not recognize `clearly` as a transition word when it was used as such.

Please add the word `clearly` to the transition words list.

**Comment by agnieszkaszuba** [comment]
The word `clearly` is not included on the transition word list because there are many cases when it is _not_ used as one. E.g.: 'The issue describes the problem very clearly.'

We cannot differentiate between the transition word uses and non-transition word uses, and we decided that including it on the list would cause too many false positives.

**Comment by monbauza** [comment]
Customer's feedback in ticket 437670

> It is quite easy to distinguish a word like "clearly" as a transition word based on its presence in the first word of a sentence, typically followed by a comma.
> Similarly with a the word "now" and is "Now, Ted is performing much better than he has in the past". This happens to be another word I discovered recently is not counted as a transition word.

**Comment by monbauza** [comment]
The same customer would like to include  'Incredibly,' 'Throughout the years,' and 'In recent years,' as transition words.

**Comment by agnieszkaszuba** [comment]
We have opened an issue about this: #2098
