### ISSUE TITLE
[Feature request] Unencode a slug on analysis check to make sure it resolves correctly

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#2211]
*Edit to make it a feature request. Please see comment below: https://github.com/Yoast/YoastSEO.js/issues/2211#issuecomment-482584320*

## What did you expect to happen?

Non-latin keywords would be recognized in slug when published

## What happened instead?

Non-latin focus keywords with characters such as Cyrillic Russian fail to be recognized in slug when published

## How can we reproduce this behavior?

**1.Create a post/page with a Russian slug**

<img width="742" alt="Screen Shot 2019-04-11 at 10 13 08 AM" src="https://user-images.githubusercontent.com/8238074/55964801-59c29780-5c43-11e9-989c-8fca9704cfb9.png">

**2.Add keyword like Забравена**

<img width="870" alt="Screen Shot 2019-04-11 at 10 19 32 AM" src="https://user-images.githubusercontent.com/8238074/55964790-53ccb680-5c43-11e9-9a88-42e2464dd97b.png">

**3.Save as draft**

**4.See keyword recognized in slug**

<img width="787" alt="Screen Shot 2019-04-11 at 10 13 00 AM" src="https://user-images.githubusercontent.com/8238074/55964850-6e069480-5c43-11e9-97bb-43778e88d565.png">

**5. See slug shown in snippet preview**

<img width="744" alt="Screen Shot 2019-04-11 at 10 13 28 AM" src="https://user-images.githubusercontent.com/8238074/55964870-75c63900-5c43-11e9-9eef-0d97bf1c4fc8.png">

**6. Publish post**

<img width="1227" alt="Screen Shot 2019-04-11 at 10 14 11 AM" src="https://user-images.githubusercontent.com/8238074/55964899-7fe83780-5c43-11e9-91de-9f0050500f02.png">

**7.See keyword not seen in slug**

<img width="743" alt="Screen Shot 2019-04-11 at 10 14 24 AM" src="https://user-images.githubusercontent.com/8238074/55964911-87a7dc00-5c43-11e9-8290-96312756c5c7.png">

**8.See slug show as unencoded in snippet preview**

<img width="713" alt="Screen Shot 2019-04-11 at 10 14 17 AM" src="https://user-images.githubusercontent.com/8238074/55964927-8f678080-5c43-11e9-95cc-4bfdbbba057c.png">

## Technical info

* Platform: WordPress  
* Platform version: 5.1.1
* Yoast SEO version: 10.1.3

Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ x] Gutenberg
- [ ] Classic Editor plugin

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/12658

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/YoastSEO.js/pull/83

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/681

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/1103

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/613

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 493529 when this conversation has been closed.

**Comment by Djennez** [comment]
Changing this to a feature request.

WordPress core encodes slugs for storage in the database. This only happens on post save and update triggers so up until that moment, a temporary version of the slug is saved which is used to check the keyphrase against. 

The feature request would be:
**Unencode a slug on analysis check to make sure it resolves correctly**

There would be several possible ways to go about this, because you don't want to trigger unencoding on a unencoded slug.
- Check the website language to see if it would contain non-latin characters and only then perform unencoding, checking the keyphrase against the original and unencoded version.
- Check for (multiple) percent "%" characters in the slug which could indicate that encoding was done to store the slug.
- Save the slug of the memory to our own database post options, just before a post update is done by WordPress, using that setting to check the keyphrase against.
- ...

**Comment by alidarkmaster** [comment]
so we should await for an update from wordpress or yoast ?

**Comment by Djennez** [comment]
@alidarkmaster I don't think WordPress is looking to change this behavior. As for Yoast, it is a feature request that may or may not get added to the plugin. So for now it is a matter of waiting for an update.

**Comment by alidarkmaster** [comment]
thank you a lot for keeping us tuned

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 566588 when this conversation has been closed.
