### ISSUE TITLE
Add subheading distribution assessment

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#343]
We recommend that a subheading is followed by 40 to 300 words. We should count the number of words following each subheading, and come up with a score. To score the distribution of subheadings, the following criteria should be met: 

Recommended minimum number of words following a subheader = 40
Recommended maximum number of words following a subheader = 300

**Calculate score (per heading):**

A subheading is followed by ≥267 words: 
```JS
score = 9 - Math.max( Math.min( ( 6 / 100 ) * ( words - 267 ), 6 ), 0 )
```

A subheading is followed by ≤53 words:
```JS
score = 3 + Math.max( Math.min( ( 6 / 40 ) * ( words - 13 ), 6 ), 0 )
```

A subheading is followed by >53 words AND <267 words: 
```JS
score = 9
```

NB: The lowest score is returned as the score for the assessment.

**Add feedback:**

`score >= 7`: “The number of words following each of your subheadings is within the recommended range, which is great.”
`score < 7`: 
- `words > 300`: “%1$d of the subheadings is followed by more than the recommended maximum of %2$d words. Try to insert another subheading.” || “%1$d of the subheadings are followed by more than the recommended maximum of %2$d words. Try to insert additional subheadings.”
- `words < 40`: “%1$d of the subheadings is followed by less than the recommended minimum of %2$d words. Consider deleting that particular subheading, or the following subheading.” || “%1$d of the subheadings are followed by less than the recommended minimum of %2$d words. Consider deleting those particular subheadings, or the subheading following each of them.”

**Comment by thoaithan95** [comment]
i don't know .[My site](http://vitinhquan7.com/sua-may-tinh-tai-nha-quan-7/) alway appear "1 of the subheadings is followed by more than the recommended maximum of 300 words. Try to insert another subheading."

**Comment by terw-dan** [comment]
@thoaithan95 
If I look at the content from the page you link, I see this:
![image](https://cloud.githubusercontent.com/assets/11272096/16338023/2967edae-3a1a-11e6-908e-aaf8a7195ca5.png)

You have a subheading `Sửa máy tính tại nhà quận 7 sẽ làm được gì ?` followed by a number of paragraphs and lists, but no other subheadings up untill right at the end where your e-mailaddress is. 

This checks looks at subheadings, `<h1>` to `<h6>`, but doesn't look at text in `<strong>`-tags, lists, paragraphs, images etc, since they aren't semantically seen as subheadings. 

I think if you replace the strong texts with real subheadings, this check will make a lot more sense.
