### ISSUE TITLE
Error highlights don't go away when fixed

### ISSUE THREAD

**Issue by jdevalk** [Yoast/YoastSEO.js#550]
### What did you expect to happen?

I had a heading of more than 30 characters. Reduced it to less, the highlight doesn't disappear.
### What happened instead?

It stayed.
### How can we reproduce this behavior?

Add a 40 character subheading to a post, highlight the error, reduce it to 30 or less characters, see that the error is still there.
### Technical info
- Platform: WordPress
- Platform version: Trunk
- Yoast SEO version: Trunk

**Comment by atimmer** [comment]
This would be super awesome, this is also very complex to build. The user experience isn't great now, so we should remove all marks when the users changes the content. See https://github.com/Yoast/wordpress-seo/issues/4708 for that.

**Comment by Djennez** [comment]
The described error has been removed from the plugin since. Highlighting of errors has also been completely revamped and with the introduction of Gutenberg there have been a lot of other changes in the analysis, highlighting and live reloading of elements. So this thread seems to be not relevant anymore which is why I will be closing it.
