### ISSUE TITLE
Transition Words Spanish - missing, and mistakes

### ISSUE THREAD

**Issue by tanirivera** [Yoast/YoastSEO.js#861]
I just checked this conversation [#769](https://github.com/Yoast/YoastSEO.js/pull/769).
I'm totally lost on how to use gihub, and excuse me if I don't know better on how to use it.

I found a few mistakes in the list of Transition Words in spanish from [this file](https://github.com/Yoast/YoastSEO.js/blob/5ee1439805bdfb6e2b4e5afb396c57d9e59bacc6/js/researches/spanish/transitionWords.js).

**Here are the mistakes:** 
como era de esperarse → como era de esperar
como es de esperarse → como es de esperar
as asií como → es así como
de la manera siguente → de la manera siguiente 
de igualmanera → they use it in latin america but it’s not in the RAE dictionary
de mismo modo → del mismo modo
dúbitamente → doesn’t exist in spanish (maybe ment súbitamente)
par terminar → para terminar
por orto lado → por otro lado

**A (long) list of missing words:**
a fin de cuentas
a fin de que
a la derecha
a la izquierda
a la vez
a lo ancho
a lo largo
a mi juicio
a mi parecer
a no ser que
a nuestro entender
abajo
ahora
ahora bien
al fondo
antes
antes bien
antes de nada
antes que nada
aquí
arriba
así pues
así y todo
aún
bueno
como decíamos
con el objeto de
con el propósito de
con referencia a
con respecto a
con tal de que
concluyendo
contrariamente
cuya
cuyos
de ello resulta que
de pronto
de suerte que
de tal modo
definitivamente
delante
desde luego
desde mi punto de vista
detrás
e
el caso es que
el cual
en aquel tiempo
en cualquier caso
en definitiva
en el caso de que
en ese momento
en este momento
en este sentido
en lo que atañe a
en lo que concierne a
en mi opinión
en otro orden
en otros términos
en resumidas cuentas
en seguida
en virtud de
encima
enfrente
enseguida
es cierto que
es evidente que
es incuestionable
es indudable
está claro que
esto es
evidentemente
excepto si
gracias a
hasta aquí
hasta el momento
incluso
justamente
las cuales
los cuales
mas
más
más abajo
más adelante
más arriba
mejor dicho
nadie puede ignorar
ni
para finalizar
pongamos por caso
por cierto
por descontado
por el consiguiente
por el hecho que
por encima
por lo que
por lo que a mi respecta
por lo que se refiere a
primero que todo
pues
queda claro
quienes
quiero decir
referente a
sea como sea
según
si
si bien
siempre y cuando
sin ir más lejos
solo que
tales como
tampoco
todo el mundo sabe
todo esto
total
un día
y

**And a [two part transition word ](https://github.com/Yoast/YoastSEO.js/blob/5ee1439805bdfb6e2b4e5afb396c57d9e59bacc6/js/researches/spanish/twoPartTransitionWords.js)missing**
bien…, bien… .

**Comment by IreneStr** [comment]
Thanks a lot, @tanirivera! Your input is much appreciated. I will take a look at it soon.

**Comment by IreneStr** [comment]
You've improved our assessment significantly, @tanirivera. Thank you!

**Comment by IreneStr** [comment]
Not included in the updated list because their transitional meaning is not strong enough, or their most frequent meaning is not transitional: 
- a la derecha (to the right)
- a la izquierda (to the left)
- a lo ancho (across/throughout)
- a lo largo(lengthways/in the distance/full out)
- a mi juicio (in my opinion)
- a mi parecer (in my view)
- a nuestro entender (in our view)
- abajo (down/below/under)
- ahora (most frequently: 'now', also: 'although')
- al fondo  (most frequently: 'at the end/back', also: 'to the truth')
- antes (most frequently: 'before/soon', also: 'rather')
- aquí (most frequently: 'here/now', also: 'at this point')
- arriba (up/above)
- bueno (most frequently: 'good/fine', also: 'Well, ...')
- con referencia a (with reference to)
- con respecto a (regarding)
- cuyos/cuya (whose, of which, in which)
- definitivamente (definitely)
- delante (in front, ahead)
- desde luego (of course, certainly)
- desde mi punto de vista (from my point of view)
- detrás (most frequently: 'behind/back/after', also: 'then')
- e (and)
- el cual (that/(in) which/who(m))
- en este momento (right now/at this moment)
- en lo que atañe a (regarding)
- en lo que concierne a (concerning)
- en mi opinión (in my opinion)
- encima (most frequently: 'upon/above/on top/up', also: 'above all/on top of that')
- enfrente (opposite/in front)
- enseguida (immediately)
- esto es (this is)
- incluso (even/including/enclosed)
- justamente (just/exactly/precisely/justly)
- las cuales/los cuales (that/(in) which/who(m))
- más (most frequently: 'more/most/', also: 'and/furthermore')
- más abajo (further/lower down)
- más adelante (further forward/below)
- más arriba (higher/further up)
- ni (or)
- por descontado (for granted)
- por lo que a mi respecta (as far as I am concerned)
- por lo que se refiere a (with regards to)
- por encima (over, beyond, overhead)
- queda claro (it's clear/becomes clear/makes clear)
- quienes (who(m), whose)
- quiero decir (I mean)
- referente a (regarding)
- según (according to)
- solo que (that only)
- todo el mundo sabe (everyone knows)
- todo esto (all these things)
- total (complete/total)
- un día (one day, day by day)
- y (and)
